package org.springframework.boot.web.embedded.tomcat;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

/* loaded from: free-market-1.0.0.jar:BOOT-INF/lib/spring-boot-2.7.12.jar:org/springframework/boot/web/embedded/tomcat/TldPatterns.class */
final class TldPatterns {
    static final Set<String> TOMCAT_SKIP;
    private static final Set<String> ADDITIONAL_SKIP;
    static final Set<String> DEFAULT_SKIP;
    static final Set<String> TOMCAT_SCAN;
    static final Set<String> DEFAULT_SCAN;

    static {
        Set<String> skipPatterns = new LinkedHashSet<>();
        skipPatterns.add("annotations-api.jar");
        skipPatterns.add("ant-junit*.jar");
        skipPatterns.add("ant-launcher*.jar");
        skipPatterns.add("ant*.jar");
        skipPatterns.add("asm-*.jar");
        skipPatterns.add("aspectj*.jar");
        skipPatterns.add("bcel*.jar");
        skipPatterns.add("biz.aQute.bnd*.jar");
        skipPatterns.add("bootstrap.jar");
        skipPatterns.add("catalina-ant.jar");
        skipPatterns.add("catalina-ha.jar");
        skipPatterns.add("catalina-ssi.jar");
        skipPatterns.add("catalina-storeconfig.jar");
        skipPatterns.add("catalina-tribes.jar");
        skipPatterns.add("catalina.jar");
        skipPatterns.add("cglib-*.jar");
        skipPatterns.add("cobertura-*.jar");
        skipPatterns.add("commons-beanutils*.jar");
        skipPatterns.add("commons-codec*.jar");
        skipPatterns.add("commons-collections*.jar");
        skipPatterns.add("commons-compress*.jar");
        skipPatterns.add("commons-daemon.jar");
        skipPatterns.add("commons-dbcp*.jar");
        skipPatterns.add("commons-digester*.jar");
        skipPatterns.add("commons-fileupload*.jar");
        skipPatterns.add("commons-httpclient*.jar");
        skipPatterns.add("commons-io*.jar");
        skipPatterns.add("commons-lang*.jar");
        skipPatterns.add("commons-logging*.jar");
        skipPatterns.add("commons-math*.jar");
        skipPatterns.add("commons-pool*.jar");
        skipPatterns.add("derby-*.jar");
        skipPatterns.add("dom4j-*.jar");
        skipPatterns.add("easymock-*.jar");
        skipPatterns.add("ecj-*.jar");
        skipPatterns.add("el-api.jar");
        skipPatterns.add("geronimo-spec-jaxrpc*.jar");
        skipPatterns.add("h2*.jar");
        skipPatterns.add("ha-api-*.jar");
        skipPatterns.add("hamcrest-*.jar");
        skipPatterns.add("hibernate*.jar");
        skipPatterns.add("httpclient*.jar");
        skipPatterns.add("icu4j-*.jar");
        skipPatterns.add("jasper-el.jar");
        skipPatterns.add("jasper.jar");
        skipPatterns.add("jaspic-api.jar");
        skipPatterns.add("jaxb-*.jar");
        skipPatterns.add("jaxen-*.jar");
        skipPatterns.add("jaxws-rt-*.jar");
        skipPatterns.add("jdom-*.jar");
        skipPatterns.add("jetty-*.jar");
        skipPatterns.add("jmx-tools.jar");
        skipPatterns.add("jmx.jar");
        skipPatterns.add("jsp-api.jar");
        skipPatterns.add("jstl.jar");
        skipPatterns.add("jta*.jar");
        skipPatterns.add("junit-*.jar");
        skipPatterns.add("junit.jar");
        skipPatterns.add("log4j*.jar");
        skipPatterns.add("mail*.jar");
        skipPatterns.add("objenesis-*.jar");
        skipPatterns.add("oraclepki.jar");
        skipPatterns.add("org.hamcrest.core_*.jar");
        skipPatterns.add("org.junit_*.jar");
        skipPatterns.add("oro-*.jar");
        skipPatterns.add("servlet-api-*.jar");
        skipPatterns.add("servlet-api.jar");
        skipPatterns.add("slf4j*.jar");
        skipPatterns.add("taglibs-standard-spec-*.jar");
        skipPatterns.add("tagsoup-*.jar");
        skipPatterns.add("tomcat-api.jar");
        skipPatterns.add("tomcat-coyote.jar");
        skipPatterns.add("tomcat-dbcp.jar");
        skipPatterns.add("tomcat-i18n-*.jar");
        skipPatterns.add("tomcat-jdbc.jar");
        skipPatterns.add("tomcat-jni.jar");
        skipPatterns.add("tomcat-juli-adapters.jar");
        skipPatterns.add("tomcat-juli.jar");
        skipPatterns.add("tomcat-util-scan.jar");
        skipPatterns.add("tomcat-util.jar");
        skipPatterns.add("tomcat-websocket.jar");
        skipPatterns.add("tools.jar");
        skipPatterns.add("unboundid-ldapsdk-*.jar");
        skipPatterns.add("websocket-api.jar");
        skipPatterns.add("wsdl4j*.jar");
        skipPatterns.add("xercesImpl.jar");
        skipPatterns.add("xml-apis.jar");
        skipPatterns.add("xmlParserAPIs-*.jar");
        skipPatterns.add("xmlParserAPIs.jar");
        skipPatterns.add("xom-*.jar");
        TOMCAT_SKIP = Collections.unmodifiableSet(skipPatterns);
        Set<String> skipPatterns2 = new LinkedHashSet<>();
        skipPatterns2.add("antlr-*.jar");
        skipPatterns2.add("aopalliance-*.jar");
        skipPatterns2.add("aspectjweaver-*.jar");
        skipPatterns2.add("classmate-*.jar");
        skipPatterns2.add("ehcache-core-*.jar");
        skipPatterns2.add("hsqldb-*.jar");
        skipPatterns2.add("jackson-annotations-*.jar");
        skipPatterns2.add("jackson-core-*.jar");
        skipPatterns2.add("jackson-databind-*.jar");
        skipPatterns2.add("jandex-*.jar");
        skipPatterns2.add("javassist-*.jar");
        skipPatterns2.add("jboss-logging-*.jar");
        skipPatterns2.add("jboss-transaction-api_*.jar");
        skipPatterns2.add("jcl-over-slf4j-*.jar");
        skipPatterns2.add("jdom-*.jar");
        skipPatterns2.add("jul-to-slf4j-*.jar");
        skipPatterns2.add("logback-classic-*.jar");
        skipPatterns2.add("logback-core-*.jar");
        skipPatterns2.add("rome-*.jar");
        skipPatterns2.add("spring-aop-*.jar");
        skipPatterns2.add("spring-aspects-*.jar");
        skipPatterns2.add("spring-beans-*.jar");
        skipPatterns2.add("spring-boot-*.jar");
        skipPatterns2.add("spring-core-*.jar");
        skipPatterns2.add("spring-context-*.jar");
        skipPatterns2.add("spring-data-*.jar");
        skipPatterns2.add("spring-expression-*.jar");
        skipPatterns2.add("spring-jdbc-*.jar,");
        skipPatterns2.add("spring-orm-*.jar");
        skipPatterns2.add("spring-oxm-*.jar");
        skipPatterns2.add("spring-tx-*.jar");
        skipPatterns2.add("snakeyaml-*.jar");
        skipPatterns2.add("tomcat-embed-core-*.jar");
        skipPatterns2.add("tomcat-embed-logging-*.jar");
        skipPatterns2.add("tomcat-embed-el-*.jar");
        skipPatterns2.add("validation-api-*.jar");
        ADDITIONAL_SKIP = Collections.unmodifiableSet(skipPatterns2);
        Set<String> skipPatterns3 = new LinkedHashSet<>();
        skipPatterns3.addAll(TOMCAT_SKIP);
        skipPatterns3.addAll(ADDITIONAL_SKIP);
        DEFAULT_SKIP = Collections.unmodifiableSet(skipPatterns3);
        Set<String> scanPatterns = new LinkedHashSet<>();
        scanPatterns.add("log4j-taglib*.jar");
        scanPatterns.add("log4j-web*.jar");
        scanPatterns.add("log4javascript*.jar");
        scanPatterns.add("slf4j-taglib*.jar");
        TOMCAT_SCAN = Collections.unmodifiableSet(scanPatterns);
        Set<String> scanPatterns2 = new LinkedHashSet<>();
        scanPatterns2.addAll(TOMCAT_SCAN);
        DEFAULT_SCAN = Collections.unmodifiableSet(scanPatterns2);
    }

    private TldPatterns() {
    }
}
